# Owner/author information
owner:
  name:      Vasudevan Venkateshwaran
  bio:       "Graduate student at Rensselaer Polytechnic Institute"
  email:     vasu.chemical@gmail.com
 
pygments: true
exclude: ["push.sh"]

navigation:
- text: Home
  url: /
- text: Publications
  url: /publications.html
- text: CV
  url: /assets/docs/vasu_resume_web.pdf


 # http://scholar.google.com/citations?user=zdFBoLoAAAAJ&hl=en 
