# Owner/author information
owner:
  name:           Vasudevan Venkateshwaran
  bio:            "Graduate student at Rensselaer Polytechnic Institute"
  email:          vasu.chemical@gmail.com
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

exclude: ["push.sh", "index-bkp.html", "lib", "config", "log"]
